<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <Configurations>Developer - Debug;Release - Alpha;Release - Beta;Release - Final</Configurations>
    <Platforms>x64</Platforms>
    <TargetFrameworks>net48</TargetFrameworks>
    <AssemblyTitle>BlankPlugin</AssemblyTitle>
    <Product>MovieTexture2AssetEditorPlugin</Product>
    <Copyright>Copyright © 2021</Copyright>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
    <Authors>MovieTexture2AssetEditorPlugin</Authors>
    <Company />
    <AssemblyName>MovieTexture2AssetEditorPlugin</AssemblyName>
    <RootNamespace>MovieTexture2AssetEditorPlugin</RootNamespace>
    <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=$(MSBuildProjectName)\</PathMap>
    <DebugType>embedded</DebugType>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Developer - Debug|x64' ">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Developer\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release - Alpha|x64' ">
    <OutputPath>bin\Release\Alpha\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Beta|x64'">
    <OutputPath>bin\Release\Beta\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Final|x64'">
    <OutputPath>bin\Release\Final\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="_EffectBlueprintEditorPlugin\**" />
    <Compile Remove="_FrostyToolsuite\**" />
    <EmbeddedResource Remove="_EffectBlueprintEditorPlugin\**" />
    <EmbeddedResource Remove="_FrostyToolsuite\**" />
    <None Remove="_EffectBlueprintEditorPlugin\**" />
    <None Remove="_FrostyToolsuite\**" />
    <Page Remove="_EffectBlueprintEditorPlugin\**" />
    <Page Remove="_FrostyToolsuite\**" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FrostyControls">
      <HintPath>D:\Frosty\FrostyToolsuite\FrostyEditor\bin\Developer\Debug\FrostyControls.dll</HintPath>
    </Reference>
    <PackageReference Include="LibVLCSharp.WPF" Version="3.9.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
    <Reference Include="FrostyCore">
      <HintPath>D:\Frosty\FrostyToolsuite\FrostyEditor\bin\Developer\Debug\FrostyCore.dll</HintPath>
    </Reference>
    <Reference Include="FrostyHash">
      <HintPath>D:\Frosty\FrostyToolsuite\FrostyEditor\bin\Developer\Debug\FrostyHash.dll</HintPath>
    </Reference>
    <Reference Include="FrostyModSupport">
      <HintPath>D:\Frosty\FrostyToolsuite\FrostyEditor\bin\Developer\Debug\FrostyModSupport.dll</HintPath>
    </Reference>
    <Reference Include="FrostySdk">
      <HintPath>D:\Frosty\FrostyToolsuite\FrostyEditor\bin\Developer\Debug\FrostySdk.dll</HintPath>
    </Reference>
    <Reference Include="FrostyEditor">
      <HintPath>D:\Frosty\FrostyToolsuite\FrostyEditor\bin\Developer\Debug\FrostyEditor.exe</HintPath>
    </Reference>
	  <!-- For referencing the Duplication Plugin 
	  -->
    <Reference Include="DuplicationPlugin">
      <HintPath>D:\Frosty\FrostyToolsuite\FrostyEditor\bin\Developer\Debug\Plugins\DuplicationPlugin.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>

  <!--
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec
      Command="xcopy /Y $(TargetPath)
  D:\Frosty\FrostyToolsuite\FrostyEditor\bin\Developer\Debug\Plugins\" />
    </Target>
	-->

</Project>