<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <Configurations>Developer - Debug;Release - Alpha;Release - Beta;Release - Final</Configurations>
    <Platforms>x64</Platforms>
    <TargetFrameworks>net48</TargetFrameworks>
    <AssemblyTitle>BlankPlugin</AssemblyTitle>
    <Product>MovieTexture2AssetEditorPlugin</Product>
    <Copyright>Copyright © 2021</Copyright>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
    <Authors>AdamRaichu</Authors>
    <Company />
    <AssemblyName>MovieTexture2AssetEditorPlugin</AssemblyName>
    <RootNamespace>MovieTexture2AssetEditorPlugin</RootNamespace>
    <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=$(MSBuildProjectName)\</PathMap>
    <DebugType>embedded</DebugType>
    <LangVersion>12</LangVersion>
	<WeaverConfiguration>
		<Weavers>
			<Costura>
				<!-- Only embed these runtime assemblies -->
				<IncludeAssemblies>
					LibVLCSharp
					LibVLCSharp.WPF
				</IncludeAssemblies>
			</Costura>
		</Weavers>
	</WeaverConfiguration>
	<PublishSingleFile>true</PublishSingleFile>
	<SelfContained>true</SelfContained>
	<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
</PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Developer - Debug|x64' ">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Developer\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release - Alpha|x64' ">
    <OutputPath>bin\Release\Alpha\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Beta|x64'">
    <OutputPath>bin\Release\Beta\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release - Final|x64'">
    <OutputPath>bin\Release\Final\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="_EffectBlueprintEditorPlugin\**" />
    <Compile Remove="_FrostyToolsuite\**" />
    <EmbeddedResource Remove="_EffectBlueprintEditorPlugin\**" />
    <EmbeddedResource Remove="_FrostyToolsuite\**" />
    <None Remove="_EffectBlueprintEditorPlugin\**" />
    <None Remove="_FrostyToolsuite\**" />
    <Page Remove="_EffectBlueprintEditorPlugin\**" />
    <Page Remove="_FrostyToolsuite\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="LibVlc\**\*.dll" />
    <EmbeddedResource Include="LibVlc\**\*.dll" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Costura.Fody" Version="6.0.0">
		<PrivateAssets>all</PrivateAssets>
	</PackageReference>
	  <!--
	  -->
    <PackageReference Include="LibVLCSharp.WPF" Version="3.9.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
	<Reference Include="FrostyControls">
		<HintPath>D:\Frosty\FrostyToolsuite\FrostyEditor\bin\Developer\Debug\FrostyControls.dll</HintPath>
	</Reference>
    <Reference Include="FrostyCore">
      <HintPath>D:\Frosty\FrostyToolsuite\FrostyEditor\bin\Developer\Debug\FrostyCore.dll</HintPath>
    </Reference>
    <Reference Include="FrostyHash">
      <HintPath>D:\Frosty\FrostyToolsuite\FrostyEditor\bin\Developer\Debug\FrostyHash.dll</HintPath>
    </Reference>
    <Reference Include="FrostyModSupport">
      <HintPath>D:\Frosty\FrostyToolsuite\FrostyEditor\bin\Developer\Debug\FrostyModSupport.dll</HintPath>
    </Reference>
    <Reference Include="FrostySdk">
      <HintPath>D:\Frosty\FrostyToolsuite\FrostyEditor\bin\Developer\Debug\FrostySdk.dll</HintPath>
    </Reference>
    <Reference Include="FrostyEditor">
      <HintPath>D:\Frosty\FrostyToolsuite\FrostyEditor\bin\Developer\Debug\FrostyEditor.exe</HintPath>
    </Reference>
    <Reference Include="DuplicationPlugin">
      <HintPath>D:\Frosty\FrostyToolsuite\FrostyEditor\bin\Developer\Debug\Plugins\DuplicationPlugin.dll</HintPath>
    </Reference>
	<Reference Include="DuplicationPluginInjectorPlugin">
		<HintPath>.\DuplicationInjector\DuplicationPluginInjectorPlugin.dll</HintPath>
		<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	</Reference>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DuplicationInjector\" />
  </ItemGroup>

  <!--
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec
      Command="xcopy /Y $(TargetPath)
  D:\Frosty\FrostyToolsuite\FrostyEditor\bin\Developer\Debug\Plugins\" />
    </Target>
	-->

</Project>